#!/bin/sh
#  Copyright © AndreyLysikov
#  SPDX-License-Identifier: Apache-2.0
set -e

if [ "$1" = "configure" ]; then
    systemctl daemon-reload
    systemctl enable wirenhome-bridge.service
    systemctl restart wirenhome-bridge.service
fi
