#!/bin/sh
#  Copyright © AndreyLysikov
#  SPDX-License-Identifier: Apache-2.0
set -e

if [ "$1" = "remove" ]; then
    systemctl stop wirenhome-bridge.service || true
    systemctl disable wirenhome-bridge.service || true
fi
