#!/bin/sh
#  Copyright © AndreyLysikov
#  SPDX-License-Identifier: Apache-2.0
set -e

if [ "$1" = "remove" ]; then
    systemctl stop wb-homekit.service || true
    systemctl disable wb-homekit.service || true
fi
